name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EAS_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Expo CLI and EAS CLI
        run: npm install -g expo-cli eas-cli@latest

      - name: Install dependencies
        run: npm install

      - name: Confirm token is set
        run: echo "Token is set"

      - name: Check Expo login
        run: eas whoami

      - name: Build APK
        run: eas build --platform android --profile preview --non-interactive
